# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 883853ebf4c812630ecef40415bf79c6ad8973c7dd23a83d031325dfb18fc84f2f51b5308e5f404e3cf65bfa25b9c2a7945590cf6726f92b6341e853ead53113

test:
  secret_key_base: 8dabc518ed2272a0ae8c8be209f7eab0ead5f88e3a34b1b24e8bc85f5d0802313805307ee16c06a7852e40d474b797e0c5584dbe752defe98680963ad30ca55f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
